name: Cleanup Untagged Docker Images

on:
  schedule:
    - cron: '0 0 * * 0' # 每周一次
  workflow_dispatch: # 手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: List and delete untagged images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PACKAGE_NAME: knowledge_backend
        run: |
          versions=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                            "https://api.github.com/orgs/$OWNER/packages/container/$PACKAGE_NAME/versions" | jq -r '.[] | @base64')

          echo "$versions" | while read version; do
            _jq() {
              echo ${version} | base64 --decode | jq -r ${1}
            }
            
            version_id=$(_jq '.id')
            tags_count=$(_jq '.metadata.container.tags | length')
            
            if [ "$tags_count" -eq "0" ]; then
              echo "Deleting untagged image with ID: $version_id"
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                   "https://api.github.com/orgs/$OWNER/packages/container/$PACKAGE_NAME/versions/$version_id"
            fi
          done
