name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    name: Release Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
      issues: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract version from package.json
        id: get_version
        run: |
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Create a tarball of the repository
        run: |
          git archive --format=tar.gz --output=repo-backup-${{ env.VERSION }}.tar.gz HEAD
            
      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag already exists"
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag does not exist"
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Set Git user info
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Create and push tag
        if: env.TAG_EXISTS == 'false'
        run: |
          git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: repo-backup-${{ env.VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
