name: Upload Latest Release Tag

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Get Latest Release Tag
        id: get_latest_release
        run: |
          # 获取最新发布的版本信息
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          LATEST_TAG=$(echo $LATEST_RELEASE | jq -r '.tag_name')
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Upload Tag to FastAPI
        env:
          FASTAPI_URL: ${{ secrets.FASTAPI_URL }} # FastAPI 服务器的 URL
        run: |
          TAG="${{ env.LATEST_TAG }}"
          echo "Tag: $TAG"

          # 上传 tag
          curl -X POST "$FASTAPI_URL/store-tag/" \
                -H "accept: application/json" \
                -H "Content-Type: application/json" \
                -d "{\"tag\": \"$TAG\"}"
